//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASN_DBEntities : DbContext
    {
        public ASN_DBEntities()
            : base("name=ASN_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Empresas> Sys_Empresas { get; set; }
        public virtual DbSet<Sys_Notificaciones> Sys_Notificaciones { get; set; }
        public virtual DbSet<Sys_Usuarios> Sys_Usuarios { get; set; }
        public virtual DbSet<Tb_Clientes> Tb_Clientes { get; set; }
        public virtual DbSet<Tb_Cotizacion_detalle> Tb_Cotizacion_detalle { get; set; }
        public virtual DbSet<Tb_Cotizaciones> Tb_Cotizaciones { get; set; }
        public virtual DbSet<Tb_Proyectos> Tb_Proyectos { get; set; }
        public virtual DbSet<Tb_Proyectos_Colaboradores> Tb_Proyectos_Colaboradores { get; set; }
        public virtual DbSet<Tb_Proyectos_Documentos> Tb_Proyectos_Documentos { get; set; }
        public virtual DbSet<Tb_Proyectos_Gastos> Tb_Proyectos_Gastos { get; set; }
    }
}
