//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Usuarios()
        {
            this.Sys_Notificaciones = new HashSet<Sys_Notificaciones>();
            this.Tb_Proyectos_Colaboradores = new HashSet<Tb_Proyectos_Colaboradores>();
        }
    
        public int ID_usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public string Posicion { get; set; }
        public string Departamentos { get; set; }
        public string Roles { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public string Url_image { get; set; }
        public int ID_empresa { get; set; }
        public bool Activo { get; set; }
        public int ID_cliente { get; set; }
    
        public virtual Sys_Empresas Sys_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Notificaciones> Sys_Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Proyectos_Colaboradores> Tb_Proyectos_Colaboradores { get; set; }
    }
}
