//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cotizacion_detalle
    {
        public int ID_detalle { get; set; }
        public string Descripcion { get; set; }
        public int Horas { get; set; }
        public decimal Costo { get; set; }
        public int ID_servicio { get; set; }
        public int ID_cotizacion { get; set; }
    
        public virtual Tb_Cotizaciones Tb_Cotizaciones { get; set; }
    }
}
