//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cotizaciones()
        {
            this.Tb_Cotizacion_detalle = new HashSet<Tb_Cotizacion_detalle>();
        }
    
        public int ID_cotizacion { get; set; }
        public int ID_cliente { get; set; }
        public string No_Cotizacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Empresa { get; set; }
        public string Telefono { get; set; }
        public int ID_empresa { get; set; }
    
        public virtual Sys_Empresas Sys_Empresas { get; set; }
        public virtual Tb_Clientes Tb_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Cotizacion_detalle> Tb_Cotizacion_detalle { get; set; }
    }
}
