//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Clientes()
        {
            this.Tb_Cotizaciones = new HashSet<Tb_Cotizaciones>();
            this.Tb_Proyectos = new HashSet<Tb_Proyectos>();
        }
    
        public int ID_cliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DUI { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string Contrasena { get; set; }
        public string Empresa { get; set; }
        public bool Lead { get; set; }
        public int ID_empresa { get; set; }
    
        public virtual Sys_Empresas Sys_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Cotizaciones> Tb_Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Proyectos> Tb_Proyectos { get; set; }
    }
}
