//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proyectos_Documentos
    {
        public int ID_documento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Extension { get; set; }
        public string Tamano { get; set; }
        public string Path { get; set; }
        public string Fecha_creacion { get; set; }
        public int ID_proyecto { get; set; }
    
        public virtual Tb_Proyectos Tb_Proyectos { get; set; }
    }
}
