//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Proyectos()
        {
            this.Tb_Proyectos_Colaboradores = new HashSet<Tb_Proyectos_Colaboradores>();
            this.Tb_Proyectos_Documentos = new HashSet<Tb_Proyectos_Documentos>();
            this.Tb_Proyectos_Gastos = new HashSet<Tb_Proyectos_Gastos>();
        }
    
        public int ID_proyecto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Notas { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public System.DateTime Fecha_finalizacon { get; set; }
        public string Tipo { get; set; }
        public string Prioridad { get; set; }
        public int ID_cliente { get; set; }
        public bool Activo { get; set; }
        public int ID_empresa { get; set; }
        public string Estado { get; set; }
    
        public virtual Sys_Empresas Sys_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Proyectos_Colaboradores> Tb_Proyectos_Colaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Proyectos_Documentos> Tb_Proyectos_Documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Proyectos_Gastos> Tb_Proyectos_Gastos { get; set; }
        public virtual Tb_Clientes Tb_Clientes { get; set; }
    }
}
