//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proyectos_Gastos
    {
        public int ID_gasto { get; set; }
        public string Concepto { get; set; }
        public decimal Valor { get; set; }
        public string Url_image { get; set; }
        public int ID_proyecto { get; set; }
    
        public virtual Tb_Proyectos Tb_Proyectos { get; set; }
    }
}
