//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asnlegalapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proyectos_Colaboradores
    {
        public int ID_detalle { get; set; }
        public int ID_usuario { get; set; }
        public int ID_proyecto { get; set; }
    
        public virtual Sys_Usuarios Sys_Usuarios { get; set; }
        public virtual Tb_Proyectos Tb_Proyectos { get; set; }
    }
}
